=== ditrit/OGrEE-Core/API/models/schemas/bldg_template_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "OGrEE Building Template Schema",
    "type": "object",
    "properties": {
        "slug": {
            "type": "string",
            "$ref": "refs/types.json#/definitions/slug"
        },
        "category": {
            "type": "string",
            "pattern": "building"
        },
        "center": {
            "type": "array",
            "items": {
                "type": "number"
            },
            "minItems": 2,
            "maxItems": 2
        },
        "sizeWDHm": {
            "type": "array",
            "items": {
                "type": "number"
            },
            "minItems": 3,
            "maxItems": 3
        },
        "vertices": {
            "type": "array",
            "items": {
                "type": "array",
                "items": {
                    "type": "number"
                },
                "minItems": 2,
                "maxItems": 2
            }
        }
    },
    "required": [
        "slug",
        "category",
        "sizeWDHm",
        "vertices",
        "center"
    ],
    "examples": [
        {
            "slug": "demo-b1",
            "category": "building",
            "sizeWDHm": [
                42,
                104,
                5
            ],
            "vertices": [],
            "center":[0,45]
        }    
    ]
}

=== ditrit/OGrEE-Core/API/models/schemas/test_data/OK/bldg_template1.json
{
    "slug"     : "demo-b1",
    "category" : "building",
    "sizeWDHm" : [80,65,3],
    "vertices" : [
        [0,0],
        [-50,0],
        [-50,-3],
        [-56,-3],
        [-60,0.2],
        [-61,-0.5],
        [-64.5,2.7],
        [-77.6,-10.3],
        [-19.8,-62.8],
        [-17.8,-62.8],
        [0,-53]
    ],
    "center": [-30,-20]
}
